### ISSUE TITLE
13

### ISSUE THREAD

**Issue by ForceTower** [GustavoHBO/MI-SD-Comunicacao-Serial-Nios#1]
https://github.com/GustavoHBO/MI-SD-Comunicacao-Serial-Nios/blob/85fc48d2dd7bbafee567b1c9820ea6e93798158d/src/modules/LCD1602.v#L266

**Comment by GustavoHBO** [comment]
kkkkk, qual foi?

**Comment by ForceTower** [comment]
14

**Comment by GustavoHBO** [comment]
14?


Gustavo Henrique / Estudante de Engenharia da Computação
ghboliveira<mailto:ghboliveira> / +55 (75) 98313-7715

Universidade Estadual de Feira de Santana
http://www.uefs.br/

[Twitter] <https://htmlsig.com/t/000001C5RAVJ>  [Facebook]  <https://htmlsig.com/t/000001CBN1XJ>  [Google +]  <https://htmlsig.com/t/000001C690BR>  [Instagram]  <https://htmlsig.com/t/000001C6HMEN>  [Skype]  <https://htmlsig.com/t/000001C6BPVZ>  [Github]  <https://htmlsig.com/t/000001CBZS8E>

________________________________
De: João Sena <notifications@github.com>
Enviado: segunda-feira, 25 de junho de 2018 20:32
Para: GustavoHBO/MI-SD-Comunicacao-Serial-Nios
Cc: Gustavo Henrique; Comment
Assunto: Re: [GustavoHBO/MI-SD-Comunicacao-Serial-Nios] 13 (#1)


14

**Comment by ForceTower** [comment]
15!

**Comment by GustavoHBO** [comment]
16!


Gustavo Henrique / Estudante de Engenharia da Computação
ghboliveira<mailto:ghboliveira> / +55 (75) 98313-7715

Universidade Estadual de Feira de Santana
http://www.uefs.br/

[Twitter] <https://htmlsig.com/t/000001C5RAVJ>  [Facebook]  <https://htmlsig.com/t/000001CBN1XJ>  [Google +]  <https://htmlsig.com/t/000001C690BR>  [Instagram]  <https://htmlsig.com/t/000001C6HMEN>  [Skype]  <https://htmlsig.com/t/000001C6BPVZ>  [Github]  <https://htmlsig.com/t/000001CBZS8E>

________________________________
De: João Sena <notifications@github.com>
Enviado: segunda-feira, 25 de junho de 2018 20:35
Para: GustavoHBO/MI-SD-Comunicacao-Serial-Nios
Cc: Gustavo Henrique; Comment
Assunto: Re: [GustavoHBO/MI-SD-Comunicacao-Serial-Nios] 13 (#1)


15!

**Comment by ForceTower** [comment]
20!

**Comment by GustavoHBO** [comment]
20?


Gustavo Henrique / Estudante de Engenharia da Computação
ghboliveira<mailto:ghboliveira> / +55 (75) 98313-7715

Universidade Estadual de Feira de Santana
http://www.uefs.br/

[Twitter] <https://htmlsig.com/t/000001C5RAVJ>  [Facebook]  <https://htmlsig.com/t/000001CBN1XJ>  [Google +]  <https://htmlsig.com/t/000001C690BR>  [Instagram]  <https://htmlsig.com/t/000001C6HMEN>  [Skype]  <https://htmlsig.com/t/000001C6BPVZ>  [Github]  <https://htmlsig.com/t/000001CBZS8E>

________________________________
De: João Sena <notifications@github.com>
Enviado: segunda-feira, 25 de junho de 2018 20:37
Para: GustavoHBO/MI-SD-Comunicacao-Serial-Nios
Cc: Gustavo Henrique; Comment
Assunto: Re: [GustavoHBO/MI-SD-Comunicacao-Serial-Nios] 13 (#1)


20!

**Comment by ForceTower** [comment]
21!

**Comment by GustavoHBO** [comment]
21.5

**Comment by ForceTower** [comment]
23.75

**Comment by GustavoHBO** [comment]
$open1



Gustavo Henrique / Estudante de Engenharia da Computação
ghboliveira<mailto:ghboliveira> / +55 (75) 98313-7715

Universidade Estadual de Feira de Santana
http://www.uefs.br/

[Twitter] <https://htmlsig.com/t/000001C5RAVJ>  [Facebook]  <https://htmlsig.com/t/000001CBN1XJ>  [Google +]  <https://htmlsig.com/t/000001C690BR>  [Instagram]  <https://htmlsig.com/t/000001C6HMEN>  [Skype]  <https://htmlsig.com/t/000001C6BPVZ>  [Github]  <https://htmlsig.com/t/000001CBZS8E>

________________________________
De: João Sena <notifications@github.com>
Enviado: terça-feira, 26 de junho de 2018 06:26
Para: GustavoHBO/MI-SD-Comunicacao-Serial-Nios
Cc: Gustavo Henrique; Comment
Assunto: Re: [GustavoHBO/MI-SD-Comunicacao-Serial-Nios] 13 (#1)


Closed #1<https://github.com/GustavoHBO/MI-SD-Comunicacao-Serial-Nios/issues/1>.
